### ISSUE TITLE
Unable to install using yarn nor npm

### ISSUE THREAD

**Issue by nudzg** [binao/ra-ror-jsonapi-client#1]
Hello,

Trying to use yarn to add the dependency I get this:

❯ yarn add ra-ror-jsonapi-client
yarn add v1.12.3
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/ra-ror-jsonapi-client: Not found".

With npm:

❯ npm i ra-ror-jsonapi-client                                                                                                                   ⏎ ✱
npm ERR! code E404
npm ERR! 404 Not Found: ra-ror-jsonapi-client@latest

README should be updated if package is not installable the way it is advertised.

Thank you!

**Comment by thoughtpunch** [comment]
try `npm install binao/ra-ror-jsonapi-client`
